#!/bin/bash

serverIp=192.168.0.99
serverUser=pi
serverPassword="raspberry"
serverOpenhabPath="/etc/openhab2/"

localOpenhabPath="$PWD/openhab2/"

folderArray=(
    "items/"
#    "things/"
    "rules/"
    "sitemaps/"
    )

for folder in "${folderArray[@]}"
do
    echo "Update Source: $localOpenhabPath$folder Destination: $serverOpenhabPath$folder"
	sshpass -p $serverPassword ssh $serverUser@$serverIp "rm -f $serverOpenhabPath$folder"
    sshpass -p $serverPassword scp $localOpenhabPath$folder* $serverUser@$serverIp:$serverOpenhabPath$folder
    sshpass -p $serverPassword ssh $serverUser@$serverIp "sudo chmod -R a=rwx $serverOpenhabPath$folder"
done

